services:
  postgres-pgbackrest:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: fin-db-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ${MOUNT_PATH}:/var/lib/postgresql
      - ${PGBACKREST_BACKUP_PATH}:/var/lib/pgbackrest
      - ${PGBACKREST_CONF}:/etc/pgbackrest/pgbackrest.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
